### ISSUE TITLE
Teacher Review Week 8

### ISSUE THREAD

**Issue by SamiDeshatty** [alvinzhengq/AP-CSA-T1#32]
Link to Presentation: https://docs.google.com/presentation/d/1kWHEpBN9ECS83AXJ4RdohwvjDW8IjF2hh27yYia99CI/edit?usp=sharing

PBL:
Frontend work: 
- [x] Working Login Page
- [ ]  API connected genre page
      - [x] System for users to select genres
      - [x] Genres are sorted into array for later use
      - [ ] Genres are used to sort data returned by API
- [x]  Basic HTML pages based on Design Document and Wireframe
            -[x] Music Page
            -[x] Login Page
            -[x] Movies Page
            -[x] Genre Page
            -[x] Main Page
 
Backend work:
- [ ] Password and Username storage
- [x] Deployment on Raspberry pi

Small Team MiniLabs:
- [x] ASCII Art Minilab
- [x]  Grayscale of Image
- [x]  Blocks using 2D Arrays
- [x]  Converting Grayscale to ASCII

Individual Work:
- [x] Unit 8 College Board

**Comment by 4disease** [comment]
The use of APIs to get all this content is pretty smart. I just wonder about copyright haha. Regardless, good job on deployment and cool idea!

**Comment by iBraskyy** [comment]
Good job guys. For some reason it's giving me blockbuster vibes -- in a good way. The format of the cards looks nice with the songs. Usage of APIs for music fetching is awesome.

**Comment by yajatyadav** [comment]
I like how you guys are using the Spotify API to get the latest songs. I would recommend adding some options to sort the songs, such as by artist, genre, duration, etc.

**Comment by Uhpachee** [comment]
I think the project theme and frontend look really good, and the use of API and databases are very useful. The website looks very easy to use and shows the necessary information.

**Comment by ChiefGuap** [comment]
This is a really awesome idea, as I really love the latest music feature as this is so so cool! The API used here is a very smart way to establish and create that page! Overall, your project is awesome and I loved the idea!

**Comment by BillyCherres** [comment]
Wow your depoloyment method is super cool. I am going to look into it if I keep having problems. Also I really like your project idea

**Comment by LordRoop** [comment]
FINALLY! A GOOD PLACE TO FIND NEW MOVIES!!!

The UI is very simple and professional. The use of APIs is very cool. Is it possible to sort through songs by artists or something? That could be a cool feature. Deployment looked p cool. Definitely going to look into Heroku.

**Comment by chenxin-chex** [comment]
The code for getting information from the spotify api seems really smart. I also like the color scheme and organization

**Comment by paul-bokelman** [comment]
great job

**Comment by Akshay-Rohatgi** [comment]
Feedback was used to improve application
