### ISSUE TITLE
Fetch latest movies based on user genre preference

### ISSUE THREAD

**Issue by Akshay-Rohatgi** [alvinzhengq/AP-CSA-T1#36]

**Comment by Akshay-Rohatgi** [comment]
Fetching the latest movies based on user genre preference using https://www.themoviedb.org/?language=en-US

Movies are generated based on preferences that the user selects, then API is used to fetch new movies that are made up of those chosen categories. 

Extra genre-selection page is no longer needed, will be removed in a later commit.

**Comment by Akshay-Rohatgi** [comment]
CSS formatting is needed for better user experience

**Comment by alvinzhengq** [comment]
https://github.com/alvinzhengq/AP-CSA-T1/commit/1e02a6eb9f1866bff13cad459bda25625a0cdba2
