### ISSUE TITLE
Dynamic Latest Music Page

### ISSUE THREAD

**Issue by alvinzhengq** [alvinzhengq/AP-CSA-T1#39]
The goal is to fetch the latest top-played music from Spotify. This is done through a series of API requests and then filtering all that information with Java and Javascript to display to the user.

**Comment by alvinzhengq** [comment]
https://github.com/alvinzhengq/AP-CSA-T1/commit/0c5663bc6cd8ad91a5dd34c171524677276f944f

**Comment by Akshay-Rohatgi** [comment]
Completed
